<a href="https://colab.research.google.com/github/dymiyata/python-pro-intro-to-ml-spring-2026/blob/main/intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

NumPy (Numerical Python) is a Python library for handling numerical data in Python.

Let's import it.

In [2]:
import numpy as np

The fundamental data structure that NumPy uses to store and manipulate data is a NumPy array. We can create one from a Python list by using `np.array(some_list)`.

In [3]:
a = [1, "hello", 87, True] # A list but not an array
print(a[3])

True


In [4]:
# Arrays can only have one data type
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

Unlike Python lists, NumPy arrays are *true* arrays in the computer science sense. Specifically:
- all elements of the array must have the same data type (e.g. `int64`, `float64`, `bool_`, `str_`, etc...)
  - NumPy will try to automatically detect the data type for elements of a given array
  - You can also manually specify it and NumPy will try its best to convert to the specified data type.
  - To specify the data type, add the `dtype` argument to the `np.array` function
  - To check the data type, you can run `array.dtype`
- The array is stored in a contiguous block of memory with only enough space to store the array itself.
  - This means if you want to add elements to the array (i.e. make the array bigger), you need to create a completely new array.

In [5]:
a = np.array([1,2,3,4])
b = np.append(a, 5)
print(a)
print(b)

[1 2 3 4]
[1 2 3 4 5]


### Multidimensional Arrays

Sometimes, we want to organize our data in multiple dimensions (like in a table or a matrix). NumPy arrays can be multidimensional!  For now, we will just focus on 1D and 2D arrays, but you can make higher dimensional arrays too.

To create a 2D array, you can again use the `np.array()` function, but this time, input a list of lists (the "rows" of your array).

In [6]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a[0, 1])
print(a[1, 2])

2
6


To check the dimensions of an array, we can use the command `array.shape`.  If it's a 2D array, it will return a pair where the first coordinate is the number of rows and the second coordinate is the number of columns.

In [7]:
a.shape

(2, 3)

### Array Creation Helper Functions

There are some nice helper functions for creating arrays.

We can use `np.zeros(shape)` to create an array of all zeros with the specified shape.

In [8]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Similarly, we can use `np.ones()` to create an array of all ones.

In [9]:
print(np.ones((5, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


For other values, we can use `np.full()` in a similar way.  However, we need to specificy the fill value as a second argument.

Let's try to make a $4 \times 5$ array where all the entries are 9.

In [10]:
print(np.full((4,5), 9))

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [11]:
print(np.full((2,3), np.pi))

[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]


With `np.full`, you can even use a list as the specified value to get an array where all of the rows are the same.

In [19]:
np.full((3,5), [1,2,3,4,5])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

We can use `np.arange()` (read as "a-range" not "arrange") to get an array of evenly spaced values.  It behaves much like the Python `range()` function.
- Here we specify a starting value, a stopping value, and a step size.  
- `np.arange()` will create a 1D array starting at the starting value, in steps equal to the step size.  It will stop at the last step which is *strictly smaller* than the stopping value.

In [13]:
for i in range(2, 19, 3):
  print(i)

2
5
8
11
14
17


In [12]:
print(np.arange(2, 19, 3))

[ 2  5  8 11 14 17]


Sometimes, we want evenly spaced values like `arange` gives us but rather than knowing the step size, we instead know *how many* elements we want.  In this case, it's easier to use `np.linspace` instead.  Again, we specify a starting value and a stopping value.  However, now the third argument isn't the step size, it's the number of elements we want.

In [14]:
np.linspace(2, 20, 14)

array([ 2.        ,  3.38461538,  4.76923077,  6.15384615,  7.53846154,
        8.92307692, 10.30769231, 11.69230769, 13.07692308, 14.46153846,
       15.84615385, 17.23076923, 18.61538462, 20.        ])

### Random elements

Sometimes, we don't want to use real world data because it may not be available or it may be inconvenient to gather.  Instead we might want to simulate some data by randomizing values.  The `np.random` module has many functions to help us do exactly this.

To get a random array of `float` values in the interval $[0, 1)$ from a uniform distribution, we can use `np.random.random()` with the shape of our desired array as an argument.

In [15]:
np.random.random((2,3))

array([[0.03807247, 0.97833977, 0.44060617],
       [0.2285342 , 0.43407145, 0.97396387]])

To get a random array of *normally distributed* values with a certain `mean` and `standard_deviation`, you can use `np.random.normal(mean, st_dev, shape)`.  This will also give an array of floats.

In [16]:
np.random.normal(0, 1, (2, 3))

array([[-1.00814856, -1.08490373, -0.86427747],
       [ 0.15826914,  0.30211907,  0.66228047]])

To get a random array of integers that are uniformally distributed, you can use `np.random.randint(a, b, shape)`.  This will give you integers in the interval $[a, b)$.

In [17]:
np.random.randint(0, 9, (2, 3))

array([[7, 6, 0],
       [0, 3, 4]])

Sometimes, when randomizing values, you want to *reuse* the same values later.  Or maybe you want someone else to be able to reproduce the same results with the *same* random values that you used.

This can be done with NumPy.
- It turns out all of the random values given by the `np.random` module are not truly random, then are *pseudo-random*.  Which means they appear random but if you know the entire state of the computer, there is actually a deterministic algorithm which computes the values.
- Whenever you call an `np.random` function, NumPy will first use sources of randomness from the operating system to generate a **seed**. Each possible seed has its own *random number generator* (RNG) which will then generate your values.
- Two RNG's with the same seed will always generate the same values if you run the exact same commands in the exact same order.  
- We can manually create an RNG with a specified seed if we want our values to be reproducable.

In [18]:
rng = np.random.default_rng(2026)
# Here we choose 2026 for the seed
# You could change this to any other value

Now lets run our random commands using `rng.<command>` instead of `np.random.<command>`.

In [19]:
print(rng.random((2, 3)))
print(rng.random((2, 3)))

[[0.17893481 0.63991317 0.4672684 ]
 [0.37050053 0.35491733 0.79051825]]
[[0.90514384 0.17735319 0.6527848 ]
 [0.29830277 0.9669622  0.91985016]]


Watch what happens if we reset the seed and run the same command again.

In [20]:
rng = np.random.default_rng(2026)
print(rng.random((2, 3)))
print(rng.random((2, 3)))

[[0.17893481 0.63991317 0.4672684 ]
 [0.37050053 0.35491733 0.79051825]]
[[0.90514384 0.17735319 0.6527848 ]
 [0.29830277 0.9669622  0.91985016]]


Note, if you keep running the same command without resetting the seed, you will get different values each time.  Afterall, we still want our random commands to appear random.  

However, if you reset the seed, then run all those commands in exactly the same order, then it will be the same as it was before.

### Accessing values/slices of an array

Now that we know how to create arrays, how can we access the data from them?

A 1D array behaves basically the same as a Python list.

In [21]:
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[2])
print(arr[-1])

1
3
4


If we have a 2D array, then we can access values using two indices.  For example `array[i,j]` with give the element in the `i`th row and `j`th column.

In [22]:
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [23]:
print(arr2[0, 0])
print(arr2[1, 3])
print(arr2[2, 1])

1
8
10


As you know, with Python lists you can use `:` to get slices of the list.  This works essentially the same with NumPy arrays. With 2D arrays, you can take slices of each coordinate individually.

In [26]:
arr3 = np.array([
    [2, 3, 4, 5],
    [8, 7, 6, 5],
    [1, 3, 9, 2],
    [0, 0, 2, 4]
])

print(arr3[2, :]) # index 2 row as a 1D array
print(arr3[2:3, :]) # index 2 row as a 2D array (with only one row)
print(arr3[:, 1]) # index 1 column as a 1D array
print(arr3[:, 1:2]) # index 1 column as a 2D array

[1 3 9 2]
[[1 3 9 2]]
[3 7 3 0]
[[3]
 [7]
 [3]
 [0]]


In [27]:
print(arr3[:2, :])

[[2 3 4 5]
 [8 7 6 5]]


In [28]:
print(arr3[:2, :2])

[[2 3]
 [8 7]]


In [29]:
print(arr3[:2, :2])

[[2 3]
 [8 7]]


In [30]:
print(arr3[:, 1:3])

[[3 4]
 [7 6]
 [3 9]
 [0 2]]


# Math with NumPy

One of the main reasons we use NumPy arrays is because it can do numerical operations **fast**.

Suppose we have two lists of integers and we want to add each entry of the first list to its corresponding entry in the second list and then get a resulting list.

In [28]:
list1 = list(range(10000))
list2 = list(range(0,20000,2))

Let's do it with Python lists.

In [30]:
import time
start = time.time()

# write code here
list3 = []
for i in range(len(list1)):
  list3.append(list1[i] + list2[i])

end = time.time()
print(end - start)




0.006029367446899414


Now let's do it the faster way with NumPy arrays.

In [31]:
arr1 = np.array(list1)
arr2 = np.array(list2)

import time
start = time.time()

# write code here
arr1 + arr2

end = time.time()
print(end - start)

0.0005552768707275391


NumPy does things much faster because it *vectorizes* the operation.  Essentially, it's doing all of the operations in *parallel* rather than adding each pair one at a time. (This uses more memory, but more often than not, speed is the limiting factor, not memory).